config {
  type: "assertion",
  name: "purchases_last_7_days_non_zero",
  schema: "dataform_assertions" 
}

-- The query below must return 0 rows if the assertion is TRUE (i.e., data is valid).
-- We select rows only when the purchase count is 0 (the invalid state).
SELECT
    COUNT(1) AS cnt
FROM
    ${ref("silver_purchase_traffic_source_medium")}
WHERE
    event_date_parsed BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND CURRENT_DATE()
HAVING
    cnt = 0